### ISSUE TITLE
init-lab

### ISSUE THREAD

**Issue by ADNANLH** [labs-web/lab-laravel-dusk#12]
# Init lab

## Travail à faire

- Création d'un rapport et présentation sans contenu avec les pages et leurs titres

## Livrable
- docs/index.md
- docs/présentation.md
- docs/assets/*
- docs/_layouts/*
- _config.yml
- README.json 
- README.md

**Comment by zaani12** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
