### ISSUE TITLE
init-présentation

### ISSUE THREAD

**Issue by ADNANLH** [labs-web/lab-laravel-dusk#13]

**Comment by zaani12** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue

**Comment by zaani12** [comment]
le pullrequest a une conflit

**Comment by zaani12** [comment]
- la description de la tâche n'est pas valide

**Comment by husseinbouik** [comment]
- le résultat n'est pas conforme au livrables dans la description de l'issue
